name: AFK4AI
options:
  bundleIdPrefix: com.afk4ai
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.afk4ai.AFK4AI
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_FILE: AFK4AI/Info.plist
    CODE_SIGN_ENTITLEMENTS: AFK4AI/AFK4AI.entitlements
    ENABLE_HARDENED_RUNTIME: YES

targets:
  AFK4AI:
    type: application
    platform: macOS
    sources:
      - AFK4AI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.afk4ai.AFK4AI
        INFOPLIST_FILE: AFK4AI/Info.plist
        CODE_SIGN_ENTITLEMENTS: AFK4AI/AFK4AI.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
